/** MUGA: Generated ES module mirror of TRACKING_PARAM_CATEGORIES
 * (src/lib/affiliates-data.js), for the web-cleaning-insight slice.
 *
 * A plain named-export copy of the tracking-param taxonomy used by
 * web/param-insight.js to build the per-parameter what/why breakdown,
 * without web/ importing from src/ directly (design ADR, see
 * sdd/web-cleaning-insight/design D1/D2).
 *
 * DO NOT EDIT BY HAND. Regenerate via `npm run build:web`
 * (tools/build-web.mjs), sourced from src/lib/affiliates-data.js.
 */
export const TRACKING_PARAM_CATEGORIES = {
  "utm": {
    "label": "UTM / Campaign",
    "labelKey": "category_utm_label",
    "description": "Google Analytics UTM parameters (utm_source, utm_medium, etc.)",
    "descriptionKey": "category_utm_desc",
    "params": [
      "utm_source",
      "utm_medium",
      "utm_campaign",
      "utm_content",
      "utm_term",
      "utm_id",
      "utm_source_platform",
      "utm_creative_format",
      "utm_marketing_tactic",
      "utm_compaign",
      "utm_emailid",
      "utm_email",
      "utm_newsletterid"
    ]
  },
  "ads": {
    "label": "Paid Ads Clicks",
    "labelKey": "category_ads_label",
    "description": "Click IDs from Google Ads, Facebook, TikTok, LinkedIn, Microsoft, Twitter, etc.",
    "descriptionKey": "category_ads_desc",
    "params": [
      "fbclid",
      "gclid",
      "gclsrc",
      "dclid",
      "gbraid",
      "wbraid",
      "msclkid",
      "tclid",
      "twclid",
      "srsltid",
      "li_fat_id",
      "li_extra",
      "li_source",
      "s_kwcid",
      "ef_id",
      "ttclid",
      "mscid",
      "oborigurl",
      "outbrainclickid",
      "taboola_campaign_id",
      "criteo_id",
      "gad_source",
      "fbc",
      "fbp",
      "sccid",
      "rdt_cid",
      "zemclick",
      "click_id",
      "yclid",
      "ysclid",
      "_openstat",
      "ymclid",
      "unicorn_click_id",
      "rb_clickid",
      "ndclid",
      "vmcid",
      "syclid",
      "pk_campaign",
      "pk_kwd",
      "pk_source",
      "pk_medium",
      "pk_cid",
      "mtm_campaign",
      "mtm_keyword",
      "mtm_source",
      "mtm_medium",
      "mtm_content",
      "mtm_group",
      "mtm_placement",
      "mtm_cid",
      "xtor",
      "xts",
      "at_campaign",
      "at_medium",
      "at_recipient_id",
      "at_recipient_list",
      "wt_zmc",
      "tw_source",
      "mkwid",
      "pcrid",
      "gdfms",
      "gdftrk",
      "gdffi",
      "adobe_mc_ref",
      "adobe_mc_sdid",
      "af_xp",
      "af_ad",
      "af_adset",
      "n_media",
      "n_ad_group",
      "n_keyword",
      "n_keyword_id",
      "n_campaign_type",
      "ssc_referrer",
      "kclid",
      "kakao_agent",
      "kakaotrack",
      "lpinfo",
      "adj_campaign",
      "adj_creative",
      "adj_label",
      "adj_t",
      "adjust_referrer",
      "adjust_tracker",
      "adjust_tracker_limit",
      "adsterra_clid",
      "adsterra_placement_id",
      "adfrom",
      "adc_publisher",
      "adc_token",
      "aiad_clid",
      "af_click_lookback",
      "af_force_deeplink",
      "is_retargeting",
      "ir_adid",
      "ir_campaignid",
      "ir_partnerid",
      "gad_campaignid",
      "gci",
      "gps_adid",
      "fbadid",
      "fb_comment_id",
      "action_object_map",
      "action_ref_map",
      "action_type_map",
      "tw_medium",
      "tw_profile_id",
      "btag",
      "erid",
      "external_click_id",
      "ftag",
      "jmtyclid",
      "maf",
      "rtkcid",
      "sscid",
      "usqp",
      "vs_campaign_id",
      "link_source",
      "tgclid"
    ]
  },
  "email": {
    "label": "Email Marketing",
    "labelKey": "category_email_label",
    "description": "Tracking from Klaviyo, HubSpot, Iterable, Marketo, Pardot, ActiveCampaign, etc.",
    "descriptionKey": "category_email_desc",
    "params": [
      "mc_cid",
      "mc_eid",
      "mailingid",
      "hqemail",
      "_hsenc",
      "_hsmi",
      "hsctatracking",
      "__hstc",
      "__hsfp",
      "__hssc",
      "mkt_tok",
      "_mkto_trk",
      "trkcampaign",
      "itm_campaign",
      "itm_content",
      "itm_medium",
      "itm_source",
      "itm_term",
      "_kx",
      "klaviyo_id",
      "vgo_ee",
      "pi_ad_id",
      "pi_campaign_id",
      "sfdcimpactsrc",
      "dm_i",
      "omnisendcontactid",
      "sib_id",
      "hsa_cam",
      "hsa_grp",
      "hsa_mt",
      "hsa_src",
      "hsa_ad",
      "hsa_acc",
      "hsa_net",
      "hsa_kw",
      "hsa_tgt",
      "hsa_ver",
      "bsft_clkid",
      "bsft_uid",
      "bsft_eid",
      "bsft_mid",
      "elqtrackid",
      "elqaid",
      "elqat",
      "elqcampaignid",
      "spjobid",
      "spmailingid",
      "spreportid",
      "spuserid",
      "trk_sid",
      "ml_subscriber",
      "ml_subscriber_hash",
      "__s",
      "_ke",
      "et_rid",
      "ss_email_id",
      "vero_id",
      "oly_anon_id",
      "oly_enc_id",
      "sms_click",
      "sms_source",
      "sms_uph",
      "hsa_la",
      "hsa_ol",
      "bsft_aaid",
      "bsft_ek",
      "elq",
      "elqak",
      "mindbox-click-id",
      "mindbox-message-key",
      "at_campaign_type",
      "at_creation",
      "at_emailtype",
      "at_link",
      "at_link_id",
      "at_link_origin",
      "at_link_type",
      "at_ptr_name",
      "at_send_date",
      "int_campaign",
      "int_content",
      "int_medium",
      "int_source",
      "int_term",
      "cx_click",
      "cx_recsorder",
      "cx_recswidget",
      "dpg_campaign",
      "dpg_content",
      "dpg_medium",
      "dpg_source",
      "emcs_t",
      "ems_dl",
      "ldtag_cl",
      "lt_r",
      "srclt",
      "personaclick_input_query",
      "personaclick_search_query",
      "recommended_by",
      "recommended_code",
      "user_email_address"
    ]
  },
  "social": {
    "label": "Social Media",
    "labelKey": "category_social_label",
    "description": "Tracking from Instagram, Pinterest, Snapchat, TikTok shares, etc.",
    "descriptionKey": "category_social_desc",
    "params": [
      "epik",
      "pin_unauth",
      "sc_channel",
      "sc_country",
      "sc_funnel",
      "sc_segment",
      "sc_icid"
    ]
  },
  "platform_noise": {
    "label": "Platform Noise",
    "labelKey": "category_platform_noise_label",
    "description": "Session IDs, A/B test tokens, internal routing params added by CDNs and platforms.",
    "descriptionKey": "category_platform_noise_desc",
    "params": [
      "si",
      "source",
      "clickid",
      "linkcode",
      "creativeasin",
      "lp_asin",
      "store_ref",
      "ingress",
      "sprefix",
      "cv_ct_cx",
      "__mk_es_es",
      "__mk_de_de",
      "__mk_fr_fr",
      "__mk_it_it",
      "__mk_en_us",
      "__mk_en_gb",
      "__mk_pt_br",
      "__mk_ja_jp",
      "mkevt",
      "mkcid",
      "mkrid",
      "toolid",
      "customid",
      "_gl",
      "_ga",
      "_gac",
      "tt_medium",
      "tt_content",
      "fb_action_ids",
      "fb_action_types",
      "fb_ref",
      "fb_source",
      "_branch_match_id",
      "_branch_referrer",
      "_bta_tid",
      "_bta_c",
      "sfmc_id",
      "_pos",
      "_ss",
      "_psq",
      "_sid",
      "_fid",
      "af_dp",
      "af_web_dp",
      "af_sub2",
      "af_sub3",
      "af_sub4",
      "af_sub5",
      "adjust_campaign",
      "adjust_adgroup",
      "adjust_creative"
    ]
  },
  "generic": {
    "label": "Generic Tracking",
    "labelKey": "category_generic_label",
    "description": "Common generic tracking params used across many platforms.",
    "descriptionKey": "category_generic_desc",
    "params": [
      "s_cid",
      "wickedid",
      "__io_lv",
      "_bdadid",
      "_bhlid",
      "_clde",
      "_cldee",
      "_io_session_id",
      "_ly_c",
      "_ly_r",
      "_ope",
      "_sgm_action",
      "_sgm_campaign",
      "_sgm_pinned",
      "_sgm_source",
      "_sgm_term",
      "_zucks_suid",
      "analytics_context",
      "analytics_trace_id",
      "asgtbndr",
      "bance_xuid",
      "bemobdata",
      "beyond_uzcvid",
      "beyond_uzmcvid",
      "cm_cr",
      "cm_me",
      "cmpid",
      "cstrackid",
      "cuid",
      "ebisadid",
      "ebisother1",
      "ebisother2",
      "ebisother3",
      "ebisother4",
      "ebisother5",
      "famad_xuid",
      "gfr_xid",
      "guccounter",
      "guce_referrer",
      "guce_referrer_sig",
      "janet",
      "line_uid",
      "loclid",
      "mt_adset",
      "mt_campaign",
      "mt_click_id",
      "mt_creative",
      "mt_link_id",
      "mt_medium",
      "mt_network",
      "mt_sub1",
      "mt_sub2",
      "mt_sub3",
      "mt_sub4",
      "mt_sub5",
      "nb_expid_meta",
      "nb_placement",
      "nx_source",
      "oprtrack",
      "pk_vid",
      "spot_im_redirect_source",
      "tcsack",
      "uzcid",
      "vc_lpp",
      "vero_conv",
      "vsm_cid",
      "vsm_pid",
      "vsm_type",
      "winflncrtag",
      "yj_r",
      "ymid"
    ]
  }
};
