#!/usr/bin/env node
/**
 * MUGA: add-rule — interactive helper to add a tracking parameter (#335).
 *
 * Lowers the contributor bar to add a single param to MUGA's universal
 * strip set. Edits the source database, generates a regression test,
 * runs the build + test suites, and leaves the diff staged for review.
 *
 * Usage:
 *
 *   npm run add-rule
 *   npm run add-rule -- --name=utm_b64url --category=utm
 *   npm run add-rule -- --name=foo --category=misc --source=https://example.com/article?foo=tracking
 *
 * What the script changes (in this order):
 *
 *   1. src/lib/affiliates.js
 *      - Appends the param to the flat `TRACKING_PARAMS` array
 *      - Appends the param to the matching `TRACKING_PARAM_CATEGORIES.<cat>.params` array
 *   2. src/rules/tracking-params.json
 *      - Regenerated by `npm run compile:rules` so DNR stays in sync
 *   2b. src/rules/rules-manifest.json
 *      - Regenerated by the same `npm run compile:rules` invocation
 *   3. src/content/cleaner-bundle.js
 *      - Regenerated by `npm run build:content` so the content-script
 *        bundle stays in sync (the CI bundle-sync gate would catch a
 *        forgotten regen, but doing it here keeps the diff complete)
 *   4. tests/unit/cleaner-add-rule-regression.test.mjs
 *      - Appends a regression entry asserting the param strips on a
 *        synthetic URL. The file accumulates rules over time — it's
 *        the audit trail of every param ever landed via this script.
 *
 * What it does NOT do:
 *
 *   - Commit. The diff is staged so the contributor can review before
 *     committing. `git commit` is a deliberate human step.
 *   - Per-domain `stripParams` / `preserveParams` edits — those need
 *     judgment about functional vs tracking on a specific host. Out
 *     of scope for the v1 of this script (deliberately).
 *   - Auto-PR. Mantenedor in the loop.
 *
 * Exit codes:
 *   0 — rule added, build + tests green, diff staged
 *   1 — invalid input, build/test failure, or unexpected file shape
 */

import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import { execSync } from "node:child_process";
import readline from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..");
const AFFILIATES_PATH = join(REPO_ROOT, "src", "lib", "affiliates.js");
const TEST_PATH = join(REPO_ROOT, "tests", "unit", "cleaner-add-rule-regression.test.mjs");

// Must match the keys of TRACKING_PARAM_CATEGORIES in src/lib/affiliates.js.
// Edits to that map must update this list (or the validation flips false).
const CATEGORIES = ["utm", "ads", "email", "social", "platform_noise", "generic"];

// Param name shape we accept: identifier-like, plus underscores and dashes.
// A few real-world params start with `_` (e.g. `_kx`, `_branch_match_id`),
// so we allow leading underscore. Numbers are allowed except as the very
// first character.
const PARAM_NAME_RE = /^[a-zA-Z_][a-zA-Z0-9_-]*$/;

function parseFlags(argv) {
  const out = {};
  for (const arg of argv) {
    const m = arg.match(/^--([^=]+)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

async function promptOnce(rl, question, validate) {
  while (true) {
    const answer = (await rl.question(question)).trim();
    if (!validate || validate(answer)) return answer;
    process.stdout.write(`  ✗ invalid — try again.\n`);
  }
}

async function gatherInput(flags) {
  // Open a readline only if we need it.
  const need = !flags.name || !flags.category;
  let rl = null;
  if (need) rl = readline.createInterface({ input: stdin, output: stdout });

  const name = flags.name
    ?? await promptOnce(rl, "Param name (e.g. utm_b64url): ", (v) => PARAM_NAME_RE.test(v));
  if (!PARAM_NAME_RE.test(name)) {
    throw new Error(`invalid param name: ${name}`);
  }

  const category = flags.category
    ?? await promptOnce(rl, `Category (${CATEGORIES.join(" / ")}): `, (v) => CATEGORIES.includes(v));
  if (!CATEGORIES.includes(category)) {
    throw new Error(`invalid category "${category}" — must be one of: ${CATEGORIES.join(", ")}`);
  }

  // Source/context is documentation only — pasted into the regression
  // test's comment so the audit trail says where the param came from.
  const source = flags.source
    ?? (rl ? await rl.question("Source/context (optional, e.g. URL or AdGuard rule): ") : "");

  if (rl) rl.close();
  return { name, category, source: (source || "").trim() };
}

// ── File mutations ───────────────────────────────────────────────────────

/**
 * Insert `name` into the flat TRACKING_PARAMS array. The array's
 * structure is { with comments }; we append the new entry as a new
 * line at the end with a context comment, just before the closing `];`.
 *
 * Returns true if the file was modified, false if `name` was already
 * present (no-op — already-stripped params aren't a failure).
 */
function appendToTrackingParams(source, name, contextComment) {
  // Already-stripped detection: the literal `"name"` token appears
  // inside the TRACKING_PARAMS block somewhere.
  const exportIdx = source.indexOf("export const TRACKING_PARAMS = [");
  if (exportIdx === -1) throw new Error("affiliates.js: TRACKING_PARAMS export not found");
  const closeIdx = source.indexOf("\n];", exportIdx);
  if (closeIdx === -1) throw new Error("affiliates.js: TRACKING_PARAMS close `];` not found");
  const block = source.slice(exportIdx, closeIdx);
  const tokenRe = new RegExp(`(^|\\W)"${escapeRegExp(name)}"`);
  if (tokenRe.test(block)) {
    return { changed: false, reason: "already in TRACKING_PARAMS" };
  }
  const insertion = `\n  // Added via npm run add-rule (#335)${contextComment ? `: ${contextComment}` : ""}\n  "${name}",\n`;
  return {
    changed: true,
    next: source.slice(0, closeIdx) + insertion + source.slice(closeIdx),
  };
}

/**
 * Append `name` to the matching category's `params` array inside
 * TRACKING_PARAM_CATEGORIES. The structure is { utm: { params: [...] }, ... }.
 */
function appendToCategory(source, category, name) {
  // Locate `<category>: {` then the `params: [` inside that object.
  const catIdx = source.indexOf(`\n  ${category}: {`);
  if (catIdx === -1) throw new Error(`affiliates.js: TRACKING_PARAM_CATEGORIES.${category} not found`);
  const paramsIdx = source.indexOf("params: [", catIdx);
  if (paramsIdx === -1) throw new Error(`affiliates.js: ${category}.params not found`);
  const closeIdx = source.indexOf("\n    ],", paramsIdx);
  if (closeIdx === -1) throw new Error(`affiliates.js: ${category}.params close \`],\` not found`);
  const block = source.slice(paramsIdx, closeIdx);
  const tokenRe = new RegExp(`(^|\\W)"${escapeRegExp(name)}"`);
  if (tokenRe.test(block)) {
    return { changed: false, reason: `already in ${category}.params` };
  }
  const insertion = `\n      "${name}",`;
  return {
    changed: true,
    next: source.slice(0, closeIdx) + insertion + source.slice(closeIdx),
  };
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ── Test scaffolding ─────────────────────────────────────────────────────

const TEST_HEADER = `/**
 * MUGA — Auto-generated regression tests for params added via
 * \`npm run add-rule\` (#335).
 *
 * Each entry asserts that processUrl strips the listed param on a
 * synthetic URL with no other context. The file is the audit trail of
 * every param ever landed via the script — keep it append-only so the
 * coverage history is preserved.
 *
 * If a param needs broader coverage (per-domain rules, preserve set,
 * bounded-scope), the maintainer should write a richer test in
 * tests/unit/cleaner.test.mjs and remove the entry here.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { processUrl } from "../../src/lib/cleaner.js";

const PREFS = {
  enabled: true,
  onboardingDone: true,
  blacklist: [],
  whitelist: [],
  customParams: [],
  remoteParams: [],
  disabledCategories: [],
  stripAllAffiliates: false,
  notifyForeignAffiliate: false,
  injectOwnAffiliate: false,
};

function assertStrips(paramName, source) {
  const url = \`https://example.test/?\${paramName}=foo&keep=bar\`;
  const { cleanUrl, action } = processUrl(url, PREFS, []);
  const u = new URL(cleanUrl);
  assert.ok(!u.searchParams.has(paramName),
    \`\${paramName} should be stripped on a generic URL (source: \${source || "n/a"})\`);
  assert.equal(u.searchParams.get("keep"), "bar",
    \`non-tracking params must survive the strip\`);
  assert.equal(action, "cleaned");
}

`;

function ensureTestFile() {
  if (!existsSync(TEST_PATH)) {
    writeFileSync(TEST_PATH, TEST_HEADER);
  }
}

function appendTestEntry(name, source) {
  // Idempotency: skip if the same param already has an entry.
  const current = readFileSync(TEST_PATH, "utf8");
  const tokenRe = new RegExp(`assertStrips\\("${escapeRegExp(name)}",`);
  if (tokenRe.test(current)) return false;
  const entry =
    `test(\`${name} — added via add-rule\`, () => {\n` +
    `  assertStrips("${name}", ${JSON.stringify(source || "")});\n` +
    `});\n\n`;
  appendFileSync(TEST_PATH, entry);
  return true;
}

// ── Main ─────────────────────────────────────────────────────────────────

async function main() {
  const flags = parseFlags(process.argv.slice(2));
  const { name, category, source } = await gatherInput(flags);

  // Mutate affiliates.js in two steps so partial failure doesn't leave
  // the file half-written.
  let affSrc = readFileSync(AFFILIATES_PATH, "utf8");
  const r1 = appendToTrackingParams(affSrc, name, source);
  if (r1.changed) affSrc = r1.next;
  const r2 = appendToCategory(affSrc, category, name);
  if (r2.changed) affSrc = r2.next;
  if (r1.changed || r2.changed) {
    writeFileSync(AFFILIATES_PATH, affSrc);
    process.stdout.write(`✓ affiliates.js: TRACKING_PARAMS=${r1.changed ? "added" : "skipped"}, ${category}.params=${r2.changed ? "added" : "skipped"}\n`);
  } else {
    process.stdout.write(`✓ affiliates.js: param already present in both lists, skipping\n`);
  }

  ensureTestFile();
  const testAdded = appendTestEntry(name, source);
  process.stdout.write(`✓ test: ${testAdded ? "appended regression entry" : "already present"}\n`);

  // Regenerate downstream artifacts.
  /** @type {import("node:child_process").ExecSyncOptions} */
  const opts = { stdio: "inherit", cwd: REPO_ROOT };
  process.stdout.write(`\n→ npm run compile:rules\n`);
  execSync("npm run compile:rules", opts);
  process.stdout.write(`\n→ npm run build:content\n`);
  execSync("npm run build:content", opts);
  process.stdout.write(`\n→ npm test\n`);
  execSync("npm test", opts);

  // Stage but DO NOT commit.
  process.stdout.write(`\n→ git add (staging the diff for review)\n`);
  execSync(
    "git add src/lib/affiliates.js src/rules/tracking-params.json src/rules/rules-manifest.json src/content/cleaner-bundle.js " + TEST_PATH,
    opts,
  );

  process.stdout.write(`\n✓ Done. Review with: git diff --cached\n`);
  process.stdout.write(`  Commit when ready: git commit -m \"feat(coverage): add ${name} (#335)\"\n`);
}

main().catch((err) => {
  process.stderr.write(`add-rule: ${err.message}\n`);
  process.exit(1);
});
