/**
 * MUGA — rules-store projection drift guard (Slice 1 of rules-scope-normalization)
 *
 * `tools/rules-source/rules.json` is now the SOURCE of MUGA's rule knowledge;
 * `src/rules/domain-rules.json` and the `params` array in
 * `tools/rules-source/params.json` are PROJECTIONS of it. This test is what
 * makes that claim safe: it re-emits both artifacts from the store and compares
 * BYTES against what is committed.
 *
 * Why bytes and not structure. The artifacts feed a shipped extension, a DNR
 * ruleset regenerated by `generate-rules.mjs`, and a byte-identity mirror in
 * `web/engine/`. If the projection reproduces the committed bytes exactly, the
 * extension provably cannot have changed — which is the entire safety argument
 * for introducing the store at all. A structural comparison would pass while a
 * reformatted file broke the mirror.
 *
 * The enforcement lives here rather than in a CI shell step because that is how
 * this repo already guards generated content: `npm run check:strip` exists as a
 * developer affordance, but `strip-table-generated.test.mjs` is what actually
 * fails the build. A test also runs locally, before the push.
 *
 * Several assertions here exist because the specific mistake is easy to make and
 * silent when made: an absent `stripParams` key normalised to `[]`, a platform
 * line ending on a file `.gitattributes` pins to LF, a store entry the legacy
 * schema cannot represent being dropped instead of reported, and an unrecognised
 * action swept into the strip bucket — which would turn a param that exists to
 * be PRESERVED into one to be stripped.
 *
 * Every guard here has been mutation-tested: the corresponding breakage was
 * applied and the suite confirmed to fail. That pass caught a blind assertion of
 * its own (see the unroutable-action test), which is the reason it is worth
 * doing rather than assuming.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";

import {
  ACTIONS,
  GLOBAL_SCOPE,
  RESERVED_ACTIONS,
  emitDomainRules,
  emitParams,
  importArtifacts,
  makeEntry,
  parseStore,
  serializeStore,
} from "../../tools/rules-store.mjs";
import { renderArtifacts } from "../../tools/build-rules-store.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");

const DOMAIN_RULES_PATH = join(REPO_ROOT, "src", "rules", "domain-rules.json");
const PARAMS_PATH = join(REPO_ROOT, "tools", "rules-source", "params.json");
const STORE_PATH = join(REPO_ROOT, "tools", "rules-source", "rules.json");

const read = (file) => readFileSync(file, "utf8");

const REGENERATE = "run `npm run build:rules-store`";

// ── The committed store must project the committed artifacts ─────────

test("the store projects domain-rules.json byte-for-byte", () => {
  const store = parseStore(read(STORE_PATH));
  assert.equal(
    emitDomainRules(store),
    read(DOMAIN_RULES_PATH),
    `src/rules/domain-rules.json has drifted from tools/rules-source/rules.json — ${REGENERATE}`
  );
});

test("the store projects the params array exactly", () => {
  const store = parseStore(read(STORE_PATH));
  const committed = JSON.parse(read(PARAMS_PATH));
  assert.deepEqual(
    emitParams(store),
    committed.params,
    `tools/rules-source/params.json has drifted from the store — ${REGENERATE}`
  );
});

test("the projection never authors version, published or sig", () => {
  // Those belong to the signing flow. A regenerated `published` would
  // invalidate a signature for no reason, so the emitter returns the array only.
  const store = parseStore(read(STORE_PATH));
  const emitted = emitParams(store);
  assert.ok(Array.isArray(emitted));
  assert.ok(emitted.every((p) => typeof p === "string"));
});

// ── Round-trip losslessness, proven by re-import ─────────────────────

test("importing the committed artifacts reproduces them exactly", () => {
  // The store on disk could in principle have been hand-edited into agreeing
  // with the artifacts. Importing from scratch and re-emitting proves the
  // transform itself is lossless, independently of what is committed.
  const domainRules = JSON.parse(read(DOMAIN_RULES_PATH));
  const params = JSON.parse(read(PARAMS_PATH)).params;
  const store = importArtifacts(domainRules, params);

  assert.equal(emitDomainRules(store), read(DOMAIN_RULES_PATH));
  assert.deepEqual(emitParams(store), params);
});

test("a serialized store parses back to an identical store", () => {
  const domainRules = JSON.parse(read(DOMAIN_RULES_PATH));
  const params = JSON.parse(read(PARAMS_PATH)).params;
  const store = importArtifacts(domainRules, params);

  assert.deepEqual(parseStore(serializeStore(store)), store);
});

// ── The distinctions that are easy to normalise away ─────────────────

test("an absent stripParams stays absent and an empty one stays empty", () => {
  // The committed file carries both shapes. Collapsing them would rewrite
  // dozens of entries on the first run and bury any real change in the noise.
  const domainRules = JSON.parse(read(DOMAIN_RULES_PATH));
  const absent = domainRules.filter((d) => !Object.hasOwn(d, "stripParams"));
  const empty = domainRules.filter((d) => d.stripParams?.length === 0);
  assert.ok(absent.length > 0, "fixture assumption: some entries omit stripParams");
  assert.ok(empty.length > 0, "fixture assumption: some entries carry an empty stripParams");

  const emitted = JSON.parse(emitDomainRules(importArtifacts(domainRules, [])));
  const byDomain = new Map(emitted.map((d) => [d.domain, d]));

  for (const source of absent) {
    assert.equal(
      Object.hasOwn(byDomain.get(source.domain), "stripParams"),
      false,
      `${source.domain}: an absent stripParams was materialised`
    );
  }
  for (const source of empty) {
    assert.deepEqual(
      byDomain.get(source.domain).stripParams,
      [],
      `${source.domain}: an empty stripParams was dropped`
    );
  }
});

test("emitted bytes are LF only", () => {
  // .gitattributes pins domain-rules.json to eol=lf so the web/engine mirror
  // holds on Windows checkouts with core.autocrlf=true.
  const store = parseStore(read(STORE_PATH));
  assert.equal(emitDomainRules(store).includes("\r"), false);
  assert.equal(serializeStore(store).includes("\r"), false);
});

test("emitted files end with exactly one trailing newline", () => {
  const store = parseStore(read(STORE_PATH));
  const emitted = emitDomainRules(store);
  assert.equal(emitted.endsWith("\n"), true);
  assert.equal(emitted.endsWith("\n\n"), false);
});

// ── The seam: what the store can hold and the legacy schema cannot ───

test("the store accepts a host-scoped strip with no sibling preserve", () => {
  // The decoupling that makes Slice 2 possible: scope and action are
  // independent. domain-rules.json requires a non-empty preserveParams on every
  // entry and therefore cannot express this at all.
  const entry = makeEntry({ scope: "example.com", param: "trk", action: ACTIONS.STRIP });
  assert.deepEqual(entry, { scope: "example.com", param: "trk", action: "strip" });
});

test("emitDomainRules refuses to render it, naming scope and param", () => {
  // It must fail loudly. Synthesising `preserveParams: []` would ship a
  // silently different file; dropping the entry would lose a rule. Either
  // failure is invisible in review, which is why this is pinned.
  const store = {
    schemaVersion: 1,
    entries: [makeEntry({ scope: "example.com", param: "trk", action: ACTIONS.STRIP })],
    projection: { scopes: { "example.com": { emitStripParams: true } } },
  };

  assert.throws(
    () => emitDomainRules(store),
    (err) => err.message.includes("example.com") && err.message.includes("trk"),
    "the unrepresentable entry was not reported with its scope and param"
  );
});

test("reserved actions cannot enter the store while nothing projects them", () => {
  for (const action of RESERVED_ACTIONS) {
    assert.throws(
      () => makeEntry({ scope: "example.com", param: "tag", action }),
      (err) => err.message.includes(action),
      `action "${action}" was accepted with no projection to render it`
    );
  }
});

test("malformed entries are rejected", () => {
  assert.throws(() => makeEntry({ scope: "", param: "x", action: ACTIONS.STRIP }));
  assert.throws(() => makeEntry({ scope: "a.com", param: "", action: ACTIONS.STRIP }));
  assert.throws(() => makeEntry({ scope: "a.com", param: "x", action: "nonsense" }));
});

// ── Global scope ─────────────────────────────────────────────────────

test("global entries stay out of domain-rules.json", () => {
  const store = {
    schemaVersion: 1,
    entries: [
      makeEntry({ scope: GLOBAL_SCOPE, param: "utm_source", action: ACTIONS.STRIP }),
      makeEntry({ scope: "a.com", param: "q", action: ACTIONS.PRESERVE }),
    ],
    projection: { scopes: { "a.com": { emitStripParams: false, note: "n" } } },
  };

  const emitted = JSON.parse(emitDomainRules(store));
  assert.equal(emitted.length, 1);
  assert.equal(emitted[0].domain, "a.com");
  assert.deepEqual(emitParams(store), ["utm_source"]);
});

// ── File-level byte identity, through the real I/O path ──────────────

test("the rendered FILES are byte-identical to what is committed", () => {
  // The assertions above compare a string and an array. Neither covers
  // params.json's file bytes: its `version`/`published` fields are preserved by
  // renderParamsFile in the I/O wrapper, and a change to that function's key
  // order or indentation would slip past an array comparison entirely. This
  // test exists because a review found exactly that gap — and because the
  // earlier test was NAMED "byte-for-byte" while comparing arrays, which is a
  // worse failure than the gap itself.
  const rendered = renderArtifacts();
  assert.equal(
    rendered.domainRules,
    read(DOMAIN_RULES_PATH),
    `src/rules/domain-rules.json bytes differ — ${REGENERATE}`
  );
  assert.equal(
    rendered.params,
    read(PARAMS_PATH),
    `tools/rules-source/params.json bytes differ — ${REGENERATE}`
  );
});

// ── Validation on the way IN, not only on construction ───────────────

test("parseStore rejects a reserved action read from disk", () => {
  // makeEntry guards the construction path. The path that matters more is this
  // one: the store is the source of truth, so it is READ far more often than it
  // is built. Before this guard, a hand-edited `action: "referral"` parsed
  // cleanly and emitDomainRules rendered it into `stripParams` — silently
  // turning a param that exists to be PRESERVED into one to be stripped.
  const hostile = JSON.stringify({
    schemaVersion: 1,
    projection: { scopes: { "a.com": { emitStripParams: true, note: "n" } } },
    entries: [
      { scope: "a.com", param: "q", action: ACTIONS.PRESERVE },
      { scope: "a.com", param: "tag", action: "referral" },
    ],
  });

  assert.throws(
    () => parseStore(hostile),
    (err) => err.message.includes("referral") && err.message.includes("tag"),
    "a reserved action survived the load path"
  );
});

test("parseStore rejects an unknown action and a missing entries array", () => {
  const unknown = JSON.stringify({
    schemaVersion: 1,
    projection: { scopes: {} },
    entries: [{ scope: "a.com", param: "x", action: "nonsense" }],
  });
  assert.throws(() => parseStore(unknown), /nonsense/);

  assert.throws(
    () => parseStore(JSON.stringify({ schemaVersion: 1, projection: { scopes: {} } })),
    /entries/
  );
});

test("an unroutable action can never reach the strip bucket", () => {
  // parseStore now rejects these, but emitDomainRules is exported and callable
  // with a hand-built object. The grouping must refuse rather than sweep an
  // unrecognised action into strip via an else branch.
  // The scope carries a preserve entry ON PURPOSE. Without it the
  // no-preserve guard would throw first, and its message also contains the
  // param name — so a test asserting only on "tag" would pass even with the
  // routing restored. It has to be the ROUTING that fails, and it has to be
  // distinguishable from the other throw.
  const store = {
    schemaVersion: 1,
    entries: [
      { scope: "a.com", param: "q", action: ACTIONS.PRESERVE },
      { scope: "a.com", param: "tag", action: "referral" },
    ],
    projection: { scopes: { "a.com": { emitStripParams: true } } },
  };
  assert.throws(
    () => emitDomainRules(store),
    (err) => err.message.includes("unroutable") && err.message.includes("tag"),
    "an unrecognised action was routed instead of refused"
  );
});
