/**
 * MUGA — rules-store projection drift guard (Slice 1 of rules-scope-normalization)
 *
 * `tools/rules-source/rules.json` is now the SOURCE of MUGA's rule knowledge;
 * `src/rules/domain-rules.json` and the `params` array in
 * `tools/rules-source/params.json` are PROJECTIONS of it. This test is what
 * makes that claim safe: it re-emits both artifacts from the store and compares
 * BYTES against what is committed.
 *
 * Why bytes and not structure. The artifacts feed a shipped extension, a DNR
 * ruleset regenerated by `generate-rules.mjs`, and a byte-identity mirror in
 * `web/engine/`. If the projection reproduces the committed bytes exactly, the
 * extension provably cannot have changed — which is the entire safety argument
 * for introducing the store at all. A structural comparison would pass while a
 * reformatted file broke the mirror.
 *
 * The enforcement lives here rather than in a CI shell step because that is how
 * this repo already guards generated content: `npm run check:strip` exists as a
 * developer affordance, but `strip-table-generated.test.mjs` is what actually
 * fails the build. A test also runs locally, before the push.
 *
 * Several assertions here exist because the specific mistake is easy to make and
 * silent when made: an absent `stripParams` key normalised to `[]`, a platform
 * line ending on a file `.gitattributes` pins to LF, a store entry the legacy
 * schema cannot represent being dropped instead of reported, and an unrecognised
 * action swept into the strip bucket — which would turn a param that exists to
 * be PRESERVED into one to be stripped.
 *
 * Every guard here has been mutation-tested: the corresponding breakage was
 * applied and the suite confirmed to fail. That pass caught a blind assertion of
 * its own (see the unroutable-action test), which is the reason it is worth
 * doing rather than assuming.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";

import {
  ACTIONS,
  GLOBAL_SCOPE,
  RESERVED_ACTIONS,
  emitDomainRules,
  emitParams,
  importArtifacts,
  makeEntry,
  parseStore,
  serializeStore,
  withGlobalParams,
  withScopedFacts,
  emitScoped,
} from "../../tools/rules-store.mjs";
import {
  buildImportedStore,
  renderArtifacts,
  PUBLISH_PAYLOAD_BUDGET_BYTES,
} from "../../tools/build-rules-store.mjs";
import { MAX_PAYLOAD_BYTES } from "../../src/lib/remote-rules.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "..", "..");

const DOMAIN_RULES_PATH = join(REPO_ROOT, "src", "rules", "domain-rules.json");
const PARAMS_PATH = join(REPO_ROOT, "tools", "rules-source", "params.json");
const STORE_PATH = join(REPO_ROOT, "tools", "rules-source", "rules.json");

/** The committed store, parsed. */
const loadStore = () => parseStore(readFileSync(STORE_PATH, "utf8"));

const read = (file) => readFileSync(file, "utf8");

const REGENERATE = "run `npm run build:rules-store`";

// ── The committed store must project the committed artifacts ─────────

test("the store projects domain-rules.json byte-for-byte", () => {
  const store = parseStore(read(STORE_PATH));
  assert.equal(
    emitDomainRules(store),
    read(DOMAIN_RULES_PATH),
    `src/rules/domain-rules.json has drifted from tools/rules-source/rules.json — ${REGENERATE}`
  );
});

test("the store projects the params array exactly", () => {
  const store = parseStore(read(STORE_PATH));
  const committed = JSON.parse(read(PARAMS_PATH));
  assert.deepEqual(
    emitParams(store),
    committed.params,
    `tools/rules-source/params.json has drifted from the store — ${REGENERATE}`
  );
});

test("the projection never authors version, published or sig", () => {
  // Those belong to the signing flow. A regenerated `published` would
  // invalidate a signature for no reason, so the emitter returns the array only.
  const store = parseStore(read(STORE_PATH));
  const emitted = emitParams(store);
  assert.ok(Array.isArray(emitted));
  assert.ok(emitted.every((p) => typeof p === "string"));
});

// ── Round-trip losslessness, proven by re-import ─────────────────────

test("importing the committed artifacts reproduces them exactly", () => {
  // The store on disk could in principle have been hand-edited into agreeing
  // with the artifacts. Importing from scratch and re-emitting proves the
  // transform itself is lossless, independently of what is committed.
  const domainRules = JSON.parse(read(DOMAIN_RULES_PATH));
  const params = JSON.parse(read(PARAMS_PATH)).params;
  const store = importArtifacts(domainRules, params);

  assert.equal(emitDomainRules(store), read(DOMAIN_RULES_PATH));
  assert.deepEqual(emitParams(store), params);
});

test("a serialized store parses back to an identical store", () => {
  const domainRules = JSON.parse(read(DOMAIN_RULES_PATH));
  const params = JSON.parse(read(PARAMS_PATH)).params;
  const store = importArtifacts(domainRules, params);

  assert.deepEqual(parseStore(serializeStore(store)), store);
});

// ── The distinctions that are easy to normalise away ─────────────────

test("an absent stripParams stays absent and an empty one stays empty", () => {
  // The committed file carries both shapes. Collapsing them would rewrite
  // dozens of entries on the first run and bury any real change in the noise.
  const domainRules = JSON.parse(read(DOMAIN_RULES_PATH));
  const absent = domainRules.filter((d) => !Object.hasOwn(d, "stripParams"));
  const empty = domainRules.filter((d) => d.stripParams?.length === 0);
  assert.ok(absent.length > 0, "fixture assumption: some entries omit stripParams");
  assert.ok(empty.length > 0, "fixture assumption: some entries carry an empty stripParams");

  const emitted = JSON.parse(emitDomainRules(importArtifacts(domainRules, [])));
  const byDomain = new Map(emitted.map((d) => [d.domain, d]));

  for (const source of absent) {
    assert.equal(
      Object.hasOwn(byDomain.get(source.domain), "stripParams"),
      false,
      `${source.domain}: an absent stripParams was materialised`
    );
  }
  for (const source of empty) {
    assert.deepEqual(
      byDomain.get(source.domain).stripParams,
      [],
      `${source.domain}: an empty stripParams was dropped`
    );
  }
});

test("emitted bytes are LF only", () => {
  // .gitattributes pins domain-rules.json to eol=lf so the web/engine mirror
  // holds on Windows checkouts with core.autocrlf=true.
  const store = parseStore(read(STORE_PATH));
  assert.equal(emitDomainRules(store).includes("\r"), false);
  assert.equal(serializeStore(store).includes("\r"), false);
});

test("emitted files end with exactly one trailing newline", () => {
  const store = parseStore(read(STORE_PATH));
  const emitted = emitDomainRules(store);
  assert.equal(emitted.endsWith("\n"), true);
  assert.equal(emitted.endsWith("\n\n"), false);
});

// ── The seam that closed (#1328) ─────────────────────────────────────
//
// A host-scoped strip with no sibling preserve used to be the store's visible
// seam: it could hold one and `emitDomainRules` threw rather than render it,
// because every domain-rules.json entry was assumed to need a non-empty
// preserveParams. `rules-store.mjs` said so itself: "Slice 2 removes this
// constraint; until then it must stay visible."
//
// #1323 and #1324 made those entries ordinary, and the constraint went from
// describing the schema to shaping the data: 60 entries carried
// `preserveParams: ["q"]` invented purely to satisfy it, preserving a param
// that is not in TRACKING_PARAMS and therefore was never stripped.
//
// So the seam is gone. It gets no replacement guard: `groupByScope` only yields
// scopes that have entries, so the case a replacement would catch cannot reach
// the renderer. The invariant is asserted where it can actually fail, against
// the committed artifact, in domain-rules.test.mjs and config-integrity.test.mjs.

test("the store accepts a host-scoped strip with no sibling preserve", () => {
  // Scope and action stay independent; that decoupling is what made Slice 2
  // possible and it is unchanged.
  const entry = makeEntry({ scope: "example.com", param: "trk", action: ACTIONS.STRIP });
  assert.deepEqual(entry, { scope: "example.com", param: "trk", action: "strip" });
});

test("emitDomainRules now renders it with an empty preserveParams", () => {
  // `[]` is representable and always was: the cleaner reads
  // `(rule.preserveParams || [])`, so empty and absent behave identically.
  const store = {
    schemaVersion: 1,
    entries: [makeEntry({ scope: "example.com", param: "trk", action: ACTIONS.STRIP })],
    projection: { scopes: { "example.com": { emitStripParams: true } } },
  };

  const emitted = JSON.parse(emitDomainRules(store));
  assert.deepEqual(emitted, [
    { domain: "example.com", preserveParams: [], stripParams: ["trk"] },
  ]);
});


test("reserved actions cannot enter the store while nothing projects them", () => {
  for (const action of RESERVED_ACTIONS) {
    assert.throws(
      () => makeEntry({ scope: "example.com", param: "tag", action }),
      (err) => err.message.includes(action),
      `action "${action}" was accepted with no projection to render it`
    );
  }
});

test("malformed entries are rejected", () => {
  assert.throws(() => makeEntry({ scope: "", param: "x", action: ACTIONS.STRIP }));
  assert.throws(() => makeEntry({ scope: "a.com", param: "", action: ACTIONS.STRIP }));
  assert.throws(() => makeEntry({ scope: "a.com", param: "x", action: "nonsense" }));
});

// ── Global scope ─────────────────────────────────────────────────────

test("global entries stay out of domain-rules.json", () => {
  const store = {
    schemaVersion: 1,
    entries: [
      makeEntry({ scope: GLOBAL_SCOPE, param: "utm_source", action: ACTIONS.STRIP }),
      makeEntry({ scope: "a.com", param: "q", action: ACTIONS.PRESERVE }),
    ],
    projection: { scopes: { "a.com": { emitStripParams: false, note: "n" } } },
  };

  const emitted = JSON.parse(emitDomainRules(store));
  assert.equal(emitted.length, 1);
  assert.equal(emitted[0].domain, "a.com");
  assert.deepEqual(emitParams(store), ["utm_source"]);
});

// ── File-level byte identity, through the real I/O path ──────────────

test("the rendered FILES are byte-identical to what is committed", () => {
  // The assertions above compare a string and an array. Neither covers
  // params.json's file bytes: its `version`/`published` fields are preserved by
  // renderParamsFile in the I/O wrapper, and a change to that function's key
  // order or indentation would slip past an array comparison entirely. This
  // test exists because a review found exactly that gap — and because the
  // earlier test was NAMED "byte-for-byte" while comparing arrays, which is a
  // worse failure than the gap itself.
  const rendered = renderArtifacts();
  assert.equal(
    rendered.domainRules,
    read(DOMAIN_RULES_PATH),
    `src/rules/domain-rules.json bytes differ — ${REGENERATE}`
  );
  assert.equal(
    rendered.params,
    read(PARAMS_PATH),
    `tools/rules-source/params.json bytes differ — ${REGENERATE}`
  );
});

// ── Validation on the way IN, not only on construction ───────────────

test("parseStore rejects a reserved action read from disk", () => {
  // makeEntry guards the construction path. The path that matters more is this
  // one: the store is the source of truth, so it is READ far more often than it
  // is built. Before this guard, a hand-edited `action: "referral"` parsed
  // cleanly and emitDomainRules rendered it into `stripParams` — silently
  // turning a param that exists to be PRESERVED into one to be stripped.
  const hostile = JSON.stringify({
    schemaVersion: 1,
    projection: { scopes: { "a.com": { emitStripParams: true, note: "n" } } },
    entries: [
      { scope: "a.com", param: "q", action: ACTIONS.PRESERVE },
      { scope: "a.com", param: "tag", action: "referral" },
    ],
  });

  assert.throws(
    () => parseStore(hostile),
    (err) => err.message.includes("referral") && err.message.includes("tag"),
    "a reserved action survived the load path"
  );
});

test("parseStore rejects an unknown action and a missing entries array", () => {
  const unknown = JSON.stringify({
    schemaVersion: 1,
    projection: { scopes: {} },
    entries: [{ scope: "a.com", param: "x", action: "nonsense" }],
  });
  assert.throws(() => parseStore(unknown), /nonsense/);

  assert.throws(
    () => parseStore(JSON.stringify({ schemaVersion: 1, projection: { scopes: {} } })),
    /entries/
  );
});

test("an unroutable action can never reach the strip bucket", () => {
  // parseStore now rejects these, but emitDomainRules is exported and callable
  // with a hand-built object. The grouping must refuse rather than sweep an
  // unrecognised action into strip via an else branch.
  // The scope carries a preserve entry ON PURPOSE. Without it the
  // no-preserve guard would throw first, and its message also contains the
  // param name — so a test asserting only on "tag" would pass even with the
  // routing restored. It has to be the ROUTING that fails, and it has to be
  // distinguishable from the other throw.
  const store = {
    schemaVersion: 1,
    entries: [
      { scope: "a.com", param: "q", action: ACTIONS.PRESERVE },
      { scope: "a.com", param: "tag", action: "referral" },
    ],
    projection: { scopes: { "a.com": { emitStripParams: true } } },
  };
  assert.throws(
    () => emitDomainRules(store),
    (err) => err.message.includes("unroutable") && err.message.includes("tag"),
    "an unrecognised action was routed instead of refused"
  );
});

// ── The `scoped` section of params.json (#1221) ──────────────────────
//
// params.json is the SIGNABLE SOURCE: `sign-rules.mjs` reads it, signs the
// scoped section with its own key, and the published payload is what every
// installed extension fetches. So this projection is the last link in a chain
// that ends at a DNR rule on a user's machine, and the two properties that
// matter are that an empty store changes nothing, and that a non-empty one
// emits exactly what the signer and the runtime accept.

test("the committed store re-renders params.json byte-identically", () => {
  // The drift guard, and the reason the projection is safe to regenerate on
  // every run: whatever the store holds, re-emitting it must reproduce the
  // committed bytes exactly.
  const { params } = renderArtifacts(loadStore());
  assert.strictEqual(params, readFileSync(PARAMS_PATH, "utf8"));
});

test("a store with NO scoped facts emits no scoped key at all", () => {
  // Absent-when-empty is what let this section ship without moving a single
  // published byte, and it stays true independently of what has landed since.
  // Built from the committed store with the segment removed, so this keeps
  // meaning the same thing after a backlog import.
  const emptied = { ...loadStore() };
  delete emptied.scopedFacts;

  const rendered = JSON.parse(renderArtifacts(emptied).params);
  assert.ok(!("scoped" in rendered), "an empty store must emit no scoped key");
});

test("a landed scoped fact appears in params.json as the payload shape", () => {
  // Asserted on THIS fact rather than on the whole array: the committed store
  // carries a real backlog, and a deep-equal here would only ever be testing
  // how much of it had landed on the day the test was written.
  const store = withScopedFacts(loadStore(), [
    { scope: "muga-test.example", param: "mugaprojected", action: ACTIONS.STRIP },
    { scope: "shop.muga-test.example", param: "mugaprojected", action: ACTIONS.STRIP },
  ]);

  const rendered = JSON.parse(renderArtifacts(store).params);
  const entry = rendered.scoped.find((f) => f.param === "mugaprojected");

  assert.deepStrictEqual(entry, {
    param: "mugaprojected",
    hosts: ["muga-test.example", "shop.muga-test.example"],
  });
});

test("adding a scoped fact leaves version, published and params untouched", () => {
  // `version` and `published` belong to the signing flow and a regenerated
  // `published` would invalidate a signature for no reason. `params` is the
  // global list every deployed version already consumes: a scoped fact must not
  // be able to disturb it, because a payload that changed both at once is one
  // where the scoped half cannot be rolled back on its own.
  const committed = JSON.parse(readFileSync(PARAMS_PATH, "utf8"));
  const store = withScopedFacts(loadStore(), [
    { scope: "muga-test.example", param: "mugauntouched", action: ACTIONS.STRIP },
  ]);

  const rendered = JSON.parse(renderArtifacts(store).params);

  assert.strictEqual(rendered.version, committed.version);
  assert.strictEqual(rendered.published, committed.published);
  assert.deepStrictEqual(rendered.params, committed.params);
});

test("an import carries landed scoped facts forward instead of deleting them", () => {
  // The silent failure this exists to stop: `--import` rebuilds the store from
  // the artifacts, and params.json's `scoped` section is a LOSSY projection of
  // scopedFacts (the pivot drops provenance). Rebuilding them from it, or
  // simply not carrying them, would erase every landed fact — and the next
  // `--check` would report drift with nothing in the diff to explain it.
  const committed = loadStore();
  const landed = [
    {
      scope: "tiktok.com",
      param: "_r",
      action: ACTIONS.STRIP,
      provenance: { signals: ["adguard-tp"], firstSeenAt: "2026-09-01T00:00:00.000Z" },
    },
  ];

  const imported = buildImportedStore(
    JSON.parse(readFileSync(DOMAIN_RULES_PATH, "utf8")),
    JSON.parse(readFileSync(PARAMS_PATH, "utf8")).params,
    landed,
  );

  assert.deepStrictEqual(imported.scopedFacts, landed, "provenance must survive the round trip");
  assert.strictEqual(imported.entries.length, committed.entries.length);
});

test("an import with nothing landed leaves the store without the key", () => {
  const imported = buildImportedStore(
    JSON.parse(readFileSync(DOMAIN_RULES_PATH, "utf8")),
    JSON.parse(readFileSync(PARAMS_PATH, "utf8")).params,
    [],
  );
  assert.strictEqual(imported.scopedFacts, undefined);
});

test("params.json renders one scoped fact per line", () => {
  // Same reasoning as serializeStore's one-entry-per-line: the weekly run
  // re-offers the whole backlog and commits only the delta, so a new fact has
  // to read as a one-line diff. Expanded, ~1000 facts cover ~6800 lines and
  // bury the three that changed.
  const text = renderArtifacts(loadStore()).params;
  const scoped = JSON.parse(text).scoped ?? [];
  if (scoped.length === 0) return;

  const factLines = text.split("\n").filter((l) => /^\s{4}\{"param":/.test(l));
  assert.strictEqual(
    factLines.length,
    scoped.length,
    "every scoped fact must occupy exactly one line",
  );
});

// ── The published payload must fit what INSTALLED builds will fetch ──────────
//
// `fetchWithCap` rejects a response over `MAX_PAYLOAD_BYTES`, and that constant
// is compiled into every installed build. A payload above the bound the
// deployed fleet carries is `OVER_CAP` there: its previous params survive so
// cleaning keeps working, but the channel stops updating — the global rules
// included, not just the scoped half — until the extension auto-updates.
//
// This is not hypothetical. The first host-scoped import weighed 108 KB against
// a 50 KB bound, and it was caught by signing it by hand rather than by any
// check. These are that check.

test("the committed source signs to a payload within the publish budget", () => {
  // Simulates the SIGNED, COMPACT bytes — what fetchWithCap streams — rather
  // than the pretty-printed source, which is about twice the size. Budgeting
  // against the wrong one errs in the direction that takes the channel down.
  const source = JSON.parse(readFileSync(PARAMS_PATH, "utf8"));
  const signed = {
    ...source,
    sig: "s".repeat(96),
    ...(source.scoped ? { scopedSig: "s".repeat(96) } : {}),
  };
  const bytes = JSON.stringify(signed).length + 1;

  assert.ok(
    bytes <= PUBLISH_PAYLOAD_BUDGET_BYTES,
    `published payload would be ${bytes} bytes, over the ` +
      `${PUBLISH_PAYLOAD_BUDGET_BYTES}-byte budget by ${bytes - PUBLISH_PAYLOAD_BUDGET_BYTES}`,
  );
});

test("the publish budget stays at or below the runtime cap", () => {
  // The two move at different times — the runtime bound rises with a release,
  // the publish budget once that release has adoption — but the publisher may
  // never exceed what the client accepts.
  assert.ok(PUBLISH_PAYLOAD_BUDGET_BYTES <= MAX_PAYLOAD_BYTES);
});

test("a store whose scoped facts exceed the budget publishes a subset, not everything", () => {
  // The guard has to bite rather than warn. Built from the committed store so
  // it exercises the real projection path.
  const store = loadStore();
  const scoped = store.scopedFacts ?? [];
  if (scoped.length === 0) return;

  const rendered = JSON.parse(renderArtifacts(store).params);
  const distinctParams = new Set(scoped.map((f) => f.param)).size;

  assert.ok(
    rendered.scoped.length <= distinctParams,
    "the published section may never carry more facts than the store holds",
  );
});

test("the published subset is a PREFIX of the full projection", () => {
  // Deterministic and monotonic: raising the budget publishes more, it never
  // reshuffles what was already served. A payload that reordered on every
  // budget change would churn scopedSig and every consumer's DNR rules.
  const store = loadStore();
  if ((store.scopedFacts ?? []).length === 0) return;

  const full = emitScoped(store);
  const globalParams = new Set(emitParams(store));
  const publishable = full.filter((f) => !globalParams.has(f.param));
  const published = JSON.parse(renderArtifacts(store).params).scoped ?? [];

  assert.deepStrictEqual(published, publishable.slice(0, published.length));
});

// ── Shadowed scoped facts must not spend the budget (#1278) ──────────────────
//
// The payload's global rule (id 1001) carries no requestDomains, so it strips
// its params on every host — including the ones a scoped fact names. A scoped
// entry for a param that is also global changes NOTHING, and the budget it
// spends is cut from facts that would change something.
//
// The filter is a PROJECTION, never a deletion: params leave the global list on
// their own (the #1221 preserveParams sweep, #1263's affiliate sweep), and the
// fact has to start publishing again when one does. The last test below is what
// makes the store-side retention load-bearing rather than decorative.

/** A store with one global strip param and one host-scoped fact for the same. */
const shadowedStore = (globalParams, facts) =>
  withScopedFacts(
    {
      schemaVersion: 1,
      entries: globalParams.map((param) =>
        makeEntry({ scope: GLOBAL_SCOPE, param, action: ACTIONS.STRIP }),
      ),
      projection: { scopes: {} },
    },
    facts.map((f) => ({ ...f, action: ACTIONS.STRIP })),
  );

const publishedScoped = (store) => JSON.parse(renderArtifacts(store).params).scoped ?? [];

test("a scoped fact whose param is in the published global list is NOT published", () => {
  const store = shadowedStore(
    ["shadowed_p", "utm_source"],
    [
      { scope: "example.com", param: "shadowed_p" },
      { scope: "example.org", param: "host_only_p" },
    ],
  );

  const rendered = JSON.parse(renderArtifacts(store).params);

  assert.ok(rendered.params.includes("shadowed_p"), "the param stays in the global list");
  assert.deepStrictEqual(
    rendered.scoped,
    [{ param: "host_only_p", hosts: ["example.org"] }],
    "the globally-stripped param must not also ride in the scoped section",
  );
});

test("the committed store publishes no scoped fact its global list already strips", () => {
  const store = loadStore();
  if ((store.scopedFacts ?? []).length === 0) return;

  const globalParams = new Set(emitParams(store));
  const shadowed = publishedScoped(store).filter((f) => globalParams.has(f.param));

  assert.deepStrictEqual(shadowed, [], "inert entries are spending a bounded publish budget");
});

test("the store still HOLDS the shadowed fact — the filter is a projection", () => {
  const store = shadowedStore(["shadowed_p"], [{ scope: "example.com", param: "shadowed_p" }]);

  // Absent from the payload...
  assert.equal(publishedScoped(store).length, 0);
  // ...and present in what gets committed, which is the only copy there is.
  assert.deepStrictEqual(emitScoped(store), [{ param: "shadowed_p", hosts: ["example.com"] }]);
  assert.ok(serializeStore(store).includes("shadowed_p"));
});

test("a fact starts publishing again once its param leaves the global list", () => {
  const shadowed = shadowedStore(
    ["shadowed_p", "utm_source"],
    [{ scope: "example.com", param: "shadowed_p" }],
  );
  assert.equal(publishedScoped(shadowed).length, 0);

  // What the #1221 preserveParams sweep and #1263's affiliate sweep do: remove
  // a param from the GLOBAL list, leaving the host-anchored fact behind.
  const swept = withGlobalParams(shadowed, ["utm_source"]);

  assert.deepStrictEqual(publishedScoped(swept), [
    { param: "shadowed_p", hosts: ["example.com"] },
  ]);
});
