/**
 * MUGA: Web-cleaner-tool engine mirror drift guard (#1029, Phase 2).
 *
 * `web/engine/cleaner-bundle.js` and `web/engine/domain-rules.json` are
 * generated byte copies of their sources of truth (src/content/cleaner-
 * bundle.js and src/rules/domain-rules.json), written by `npm run
 * build:web` (tools/build-web.mjs). CI regenerates and git-diffs them
 * (see ci.yml); this test catches the same drift locally under `npm
 * test`, before a PR is even opened.
 *
 * Triangulation skipped: both assertions are structural byte-identity
 * checks (a straight file copy has exactly one correct outcome — the
 * copy matches the source, or it does not). There is no branching logic
 * to triangulate against.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");

test("web/engine/cleaner-bundle.js is byte-identical to src/content/cleaner-bundle.js", () => {
  const source = readFileSync(join(ROOT, "src/content/cleaner-bundle.js"));
  const mirror = readFileSync(join(ROOT, "web/engine/cleaner-bundle.js"));
  assert.ok(
    source.equals(mirror),
    "web/engine/cleaner-bundle.js is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/domain-rules.json is byte-identical to src/rules/domain-rules.json", () => {
  const source = readFileSync(join(ROOT, "src/rules/domain-rules.json"));
  const mirror = readFileSync(join(ROOT, "web/engine/domain-rules.json"));
  assert.ok(
    source.equals(mirror),
    "web/engine/domain-rules.json is out of sync — run 'npm run build:web' and commit the result",
  );
});
