/**
 * MUGA: Web-cleaner-tool engine mirror drift guard (#1029, Phase 2 + Phase 4).
 *
 * `web/engine/cleaner-bundle.js` and `web/engine/domain-rules.json` are
 * generated byte copies of their sources of truth (src/content/cleaner-
 * bundle.js and src/rules/domain-rules.json), written by `npm run
 * build:web` (tools/build-web.mjs). `web/engine/domain-rules.gen.mjs` is
 * a generated (transformed, not byte-copied) named-export ES module
 * mirror of the same JSON, added in Phase 4 to resolve a browser
 * JSON-import-attribute compat gap (see build-web.mjs's `Phase 4` header
 * comment). CI regenerates and git-diffs all of these (see ci.yml); this
 * test catches the same drift locally under `npm test`, before a PR is
 * even opened. Also asserts the landing/clean/ mirror stays in lockstep,
 * since `npm run build:web` copies the whole web/ tree into it.
 *
 * Triangulation skipped for the byte-identity checks: a straight file
 * copy has exactly one correct outcome — the copy matches the source, or
 * it does not. The generated-module check regenerates the expected
 * content via the same pure function the build script uses
 * (`renderDomainRulesModule`) and byte-compares it against the committed
 * file, which is the equivalent local RED for a deterministic transform.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";

import {
  renderDomainRulesModule,
  renderParamCategoriesModule,
  renderPathStripRulesModule,
} from "../../tools/build-web.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");

test("web/engine/cleaner-bundle.js is byte-identical to src/content/cleaner-bundle.js", () => {
  const source = readFileSync(join(ROOT, "src/content/cleaner-bundle.js"));
  const mirror = readFileSync(join(ROOT, "web/engine/cleaner-bundle.js"));
  assert.ok(
    source.equals(mirror),
    "web/engine/cleaner-bundle.js is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/domain-rules.json is byte-identical to src/rules/domain-rules.json", () => {
  const source = readFileSync(join(ROOT, "src/rules/domain-rules.json"));
  const mirror = readFileSync(join(ROOT, "web/engine/domain-rules.json"));
  assert.ok(
    source.equals(mirror),
    "web/engine/domain-rules.json is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/domain-rules.gen.mjs matches the deterministic rendering of src/rules/domain-rules.json", () => {
  const domainRules = JSON.parse(readFileSync(join(ROOT, "src/rules/domain-rules.json"), "utf8"));
  const expected = renderDomainRulesModule(domainRules);
  const actual = readFileSync(join(ROOT, "web/engine/domain-rules.gen.mjs"), "utf8");
  assert.equal(
    actual,
    expected,
    "web/engine/domain-rules.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("landing/clean/engine/domain-rules.gen.mjs is byte-identical to web/engine/domain-rules.gen.mjs", () => {
  const source = readFileSync(join(ROOT, "web/engine/domain-rules.gen.mjs"));
  const mirror = readFileSync(join(ROOT, "landing/clean/engine/domain-rules.gen.mjs"));
  assert.ok(
    source.equals(mirror),
    "landing/clean/engine/domain-rules.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("landing/clean/engine/param-categories.gen.mjs is byte-identical to web/engine/param-categories.gen.mjs", () => {
  const source = readFileSync(join(ROOT, "web/engine/param-categories.gen.mjs"));
  const mirror = readFileSync(join(ROOT, "landing/clean/engine/param-categories.gen.mjs"));
  assert.ok(
    source.equals(mirror),
    "landing/clean/engine/param-categories.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("landing/clean/engine/param-breakdown-view.gen.mjs is byte-identical to web/engine/param-breakdown-view.gen.mjs", () => {
  const source = readFileSync(join(ROOT, "web/engine/param-breakdown-view.gen.mjs"));
  const mirror = readFileSync(join(ROOT, "landing/clean/engine/param-breakdown-view.gen.mjs"));
  assert.ok(
    source.equals(mirror),
    "landing/clean/engine/param-breakdown-view.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/param-categories.gen.mjs matches the deterministic rendering of TRACKING_PARAM_CATEGORIES", async () => {
  const { TRACKING_PARAM_CATEGORIES } = await import(pathToFileURL(join(ROOT, "src/lib/affiliates-data.js")).href);
  const expected = renderParamCategoriesModule(TRACKING_PARAM_CATEGORIES);
  const actual = readFileSync(join(ROOT, "web/engine/param-categories.gen.mjs"), "utf8");
  assert.equal(
    actual,
    expected,
    "web/engine/param-categories.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/param-breakdown-view.gen.mjs is byte-identical to src/lib/param-breakdown-view.js", () => {
  const source = readFileSync(join(ROOT, "src/lib/param-breakdown-view.js"));
  const mirror = readFileSync(join(ROOT, "web/engine/param-breakdown-view.gen.mjs"));
  assert.ok(
    source.equals(mirror),
    "web/engine/param-breakdown-view.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/param-breakdown-view.gen.mjs has zero import statements (self-contained mirror)", () => {
  const mirror = readFileSync(join(ROOT, "web/engine/param-breakdown-view.gen.mjs"), "utf8");
  assert.ok(
    !/^\s*import /m.test(mirror),
    "web/engine/param-breakdown-view.gen.mjs must stay import-free — it is byte-copied verbatim, so its source (src/lib/param-breakdown-view.js) must never gain an import either",
  );
});

test("web/engine/path-strip-rules.json is byte-identical to src/rules/path-strip-rules.json", () => {
  const source = readFileSync(join(ROOT, "src/rules/path-strip-rules.json"));
  const mirror = readFileSync(join(ROOT, "web/engine/path-strip-rules.json"));
  assert.ok(
    source.equals(mirror),
    "web/engine/path-strip-rules.json is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("web/engine/path-strip-rules.gen.mjs matches the deterministic rendering of src/rules/path-strip-rules.json", () => {
  const pathStripRules = JSON.parse(readFileSync(join(ROOT, "src/rules/path-strip-rules.json"), "utf8"));
  const expected = renderPathStripRulesModule(pathStripRules);
  const actual = readFileSync(join(ROOT, "web/engine/path-strip-rules.gen.mjs"), "utf8");
  assert.equal(
    actual,
    expected,
    "web/engine/path-strip-rules.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("landing/clean/engine/path-strip-rules.json is byte-identical to web/engine/path-strip-rules.json", () => {
  const source = readFileSync(join(ROOT, "web/engine/path-strip-rules.json"));
  const mirror = readFileSync(join(ROOT, "landing/clean/engine/path-strip-rules.json"));
  assert.ok(
    source.equals(mirror),
    "landing/clean/engine/path-strip-rules.json is out of sync — run 'npm run build:web' and commit the result",
  );
});

test("landing/clean/engine/path-strip-rules.gen.mjs is byte-identical to web/engine/path-strip-rules.gen.mjs", () => {
  const source = readFileSync(join(ROOT, "web/engine/path-strip-rules.gen.mjs"));
  const mirror = readFileSync(join(ROOT, "landing/clean/engine/path-strip-rules.gen.mjs"));
  assert.ok(
    source.equals(mirror),
    "landing/clean/engine/path-strip-rules.gen.mjs is out of sync — run 'npm run build:web' and commit the result",
  );
});

// The landing hero morph now loads landing/clean/ui.js (and its sibling
// modules) as its REAL runtime controller, so any drift between web/ and
// landing/clean/ silently breaks the landing tool. Guard byte-parity of the
// controller modules the same way the engine artifacts above are guarded.
for (const rel of ["ui.js", "ui-view.js", "param-insight.js", "report-link.js"]) {
  test(`landing/clean/${rel} is byte-identical to web/${rel}`, () => {
    const source = readFileSync(join(ROOT, "web", rel));
    const mirror = readFileSync(join(ROOT, "landing/clean", rel));
    assert.ok(
      source.equals(mirror),
      `landing/clean/${rel} is out of sync — run 'npm run build:web' and commit the result`,
    );
  });
}
