/**
 * MUGA: wrapper-dnr-rules.json ↔ buildDnrRules sync invariants.
 *
 * Third leg of the defense-in-depth trio (companion to
 * tests/unit/cleaner-bundle-sync.test.mjs and dnr-rules-sync.test.mjs).
 * Pins the committed `src/rules/wrapper-dnr-rules.json` (generated by
 * `npm run build:dnr` per B6 / PR #504) to what `buildDnrRules(WRAPPERS)`
 * would produce today.
 *
 * If WRAPPERS in src/lib/wrapper-engine.js changes such that the
 * regex-pure subset's rule shape changes, run:
 *
 *   npm run build:dnr
 *   git add src/rules/wrapper-dnr-rules.json
 *
 * and re-run the suite. CI also gates this artifact: .github/workflows/ci.yml
 * runs `npm run build:dnr` and fails on any `git diff` in `src/rules/` (added
 * in #722), so drift is caught both here and in the pipeline.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { WRAPPERS } from "../../src/lib/wrapper-engine.js";
import { buildDnrRules, validateDnrRules } from "../../src/lib/wrapper-dnr-builder.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RULES_PATH = join(__dirname, "..", "..", "src", "rules", "wrapper-dnr-rules.json");
const COMMITTED = JSON.parse(readFileSync(RULES_PATH, "utf8"));

test("wrapper-dnr-rules.json — is a JSON array", () => {
  assert.ok(Array.isArray(COMMITTED), "wrapper-dnr-rules.json must be a JSON array");
});

test("wrapper-dnr-rules.json — committed file matches buildDnrRules(WRAPPERS) output", () => {
  const fresh = buildDnrRules(WRAPPERS);
  assert.deepEqual(
    COMMITTED,
    fresh,
    "wrapper-dnr-rules.json is out of sync with src/lib/wrapper-engine.js — run `npm run build:dnr` and commit the result",
  );
});

test("wrapper-dnr-rules.json — rule count matches live buildDnrRules(WRAPPERS) output", () => {
  // Historically each regex-pure wrapper id in REGEX_PURE_WRAPPER_IDS mapped
  // to exactly one rule, so this test compared COMMITTED.length directly to
  // REGEX_PURE_WRAPPER_IDS.length. That invariant broke in #907: three of
  // the five allowlisted ids (skimlinks-redirectingat, skimlinks-skimresources,
  // shareasale) now point at a sourceId ("skimlinks" / "shareasale") that no
  // longer exists in WRAPPERS — those recipes are dead code (see
  // src/lib/wrapper-dnr-builder.js and tests/unit/wrapper-dnr-builder.test.mjs
  // for the full explanation). buildDnrRules() is the only thing that knows
  // which allowlisted ids actually still resolve, so compare against its
  // live output instead of the static allowlist length.
  const fresh = buildDnrRules(WRAPPERS);
  assert.equal(
    COMMITTED.length,
    fresh.length,
    `expected ${fresh.length} rules from live buildDnrRules(WRAPPERS); committed file has ${COMMITTED.length}`,
  );
  assert.equal(
    COMMITTED.length,
    2,
    "expected exactly 2 rules (facebook-l, facebook-lm) — skimlinks/shareasale recipes are dead since #907",
  );
});

test("wrapper-dnr-rules.json — every rule passes validateDnrRules", () => {
  const v = validateDnrRules(COMMITTED);
  assert.equal(v.ok, true, `committed rules failed validation: ${v.warnings.join("; ")}`);
});

test("wrapper-dnr-rules.json — every regexFilter compiles as a RegExp", () => {
  for (const rule of COMMITTED) {
    const filter = rule?.condition?.regexFilter;
    assert.equal(typeof filter, "string", `rule ${rule?.id} has no regexFilter`);
    assert.doesNotThrow(
      () => new RegExp(filter),
      `rule ${rule?.id} has an invalid regexFilter: ${filter}`,
    );
  }
});

test("wrapper-dnr-rules.json — every rule uses redirect+regexSubstitution action", () => {
  for (const rule of COMMITTED) {
    assert.equal(rule.action?.type, "redirect", `rule ${rule.id} action.type must be "redirect"`);
    assert.equal(
      typeof rule.action?.redirect?.regexSubstitution,
      "string",
      `rule ${rule.id} must have action.redirect.regexSubstitution`,
    );
  }
});

test("wrapper-dnr-rules.json — every rule has resourceTypes [main_frame, sub_frame]", () => {
  for (const rule of COMMITTED) {
    assert.deepEqual(
      rule.condition?.resourceTypes,
      ["main_frame", "sub_frame"],
      `rule ${rule.id} resourceTypes must be ["main_frame","sub_frame"]`,
    );
  }
});
